services:
  odoo:
    container_name: owl-course
    image: mjavint/odoodev:3.12-slim-bookworm
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - odoo-data:/var/lib/odoo
    command: sleep infinity
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    networks:
      - shared-net

  course-pgdb:
    image: postgres:17.0
    container_name: course-pgdb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdb-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-net

volumes:
  odoo-data:
  pgdb-data:

networks:
  shared-net:
    driver: bridge
